apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-cns
  labels:
    app: azure-cns
spec:
  selector:
    matchLabels:
      app: azure-cns
  template:
    metadata:
      labels:
        app: azure-cns
    spec:
      nodeSelector:
        node-type: cnscni
      hostNetwork: true
      containers:
        - name: cns-container
          image: acnsdnrunners.azurecr.io/azure-cns:linux-amd64-v1.6.23-3-g7c218a560
          imagePullPolicy: IfNotPresent
          args:
            ["-c", "tcp://0.0.0.0:$(CNSPort)", "-t", "$(CNSLogTarget)"]
          volumeMounts:
            - name: log
              mountPath: /var/log
            - name: cns-state
              mountPath: /var/lib/azure-network
            - name: cns-config
              mountPath: /etc/azure-cns
            - name: cni-bin
              mountPath: /opt/cni/bin
            - name: azure-vnet
              mountPath: /var/run/azure-vnet
            - name: legacy-cni-state
              mountPath: /var/run/azure-vnet.json
          ports:
            - containerPort: 10090
          env:
            - name: CNSPort
              value: "10090"
            - name: CNSLogTarget
              value: "stdoutfile"
            - name: CNS_CONFIGURATION_PATH
              value: /etc/azure-cns/cns_config.json
      initContainers:
        - name: init-cni-dropgz
          image: acnsdnrunners.azurecr.io/azure-cni:linux-amd64-v1.6.23-3-g7c218a560
          imagePullPolicy: IfNotPresent
          command: ["/dropgz"]
          args:
            - deploy
            - azure-vnet
            - -o
            - /opt/cni/bin/azure-vnet
            - azure-multitenancy-transparent-vlan.conflist
            - -o
            - /etc/cni/net.d/10-azure.conflist
          volumeMounts:
            - name: cni-bin
              mountPath: /opt/cni/bin
            - name: cni-conflist
              mountPath: /etc/cni/net.d
      volumes:
        - name: log
          hostPath:
            path: /var/log
            type: Directory
        - name: cns-state
          hostPath:
            path: /var/lib/azure-network
            type: DirectoryOrCreate
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
            type: Directory
        - name: cni-conflist
          hostPath:
            path: /etc/cni/net.d
            type: Directory
        - name: azure-vnet
          hostPath:
            path: /var/run/azure-vnet
            type: DirectoryOrCreate
        - name: legacy-cni-state
          hostPath:
            path: /var/run/azure-vnet.json
            type: FileOrCreate
        - name: cns-config
          configMap:
            name: cns-config
