apiVersion: v1
kind: Pod
metadata:
  name: container1-pod
  labels:
    app: container1pod
spec:
  containers:
  - name: container1
    image: acnsdnrunners.azurecr.io/workerlinux:v0.0.7
    ports:
    - containerPort: 443
      protocol: TCP
    - containerPort: 8080
      protocol: TCP
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
  - name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 36000; done"]
  nodeSelector:
    cx: vm1
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: ${RESOURCE_GROUP}
    service.beta.kubernetes.io/azure-pip-name: container1PublicIP
spec:
  type: LoadBalancer
  selector:
    app: container1pod
  ports:
  - protocol: TCP
    name: port1
    port: 443       # Publicly accessible port
    targetPort: 443 # Port on the container
  - protocol: TCP
    name: port2
    port: 8080      # Publicly accessible port
    targetPort: 8080 # Port on the container