apiVersion: v1
kind: Pod
metadata:
  name: gccontainer-pod
  labels:
    app: gccontainerpod
spec:
  containers:
  - name: gccontainer
    image: acndev.azurecr.io/runnertinyproxy:latest
    ports:
    - containerPort: 8888
      protocol: TCP
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
  - name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 36000; done"]
  nodeSelector:
    cx: vm1
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: gccontainer-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: ${RESOURCE_GROUP}
    service.beta.kubernetes.io/azure-pip-name: gccontainerPublicIP
spec:
  type: LoadBalancer
  selector:
    app: gccontainerpod
  ports:
  - protocol: TCP
    name: port1
    port: 8888      # Publicly accessible port
    targetPort: 8888 # Port on the container
